name: Trigger auto deployment for videoinfo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/videoinfo-AutoDeployTrigger-454e41c1-487d-4740-baec-31834d1d4801.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bondtowertransit.azurecr.io
          username: ${{ secrets.VIDEOINFO_REGISTRY_USERNAME }}
          password: ${{ secrets.VIDEOINFO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bondtowertransit.azurecr.io/videoinfo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.VIDEOINFO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n videoinfo -g bondvideoinfo --server bondtowertransit.azurecr.io --username  ${{ secrets.VIDEOINFO_REGISTRY_USERNAME }} --password ${{ secrets.VIDEOINFO_REGISTRY_PASSWORD }}
            az containerapp update -n videoinfo -g bondvideoinfo --image bondtowertransit.azurecr.io/videoinfo:${{ github.sha }}
